### PR TITLE
I made some changes by adding the shipping discount feature

### PR DESCRIPTION
**Pull request by peterchaula**

### CODE REVIEW

**Comment by brycelarge** [comment]
Your commit "Add action to load custom scripts", could you not rather include the JavaScript in the mds_collivery.js file?

**Comment by brycelarge** [comment]
Your commit "New class that handles discount calculations" seems excessive to create an entire class to calculate the discount, can this not be included into the MdsColliveryService.php file, this file already contains the settings and everything you need.

**Comment by brycelarge** [comment]
The rest all looks good

**Comment by peterchaula** [comment]
> "seems excessive to create an entire class to calculate the discount, can this not be included into the MdsColliveryService.php file, this file already contains the settings and everything you need."

Good idea that, thank you. I'll try to refactor it in. However, I am just not a firm believer of **"god objects"** that handle everything. I prefer responsibility driven design. A small class would be usable across the whole project. It wouldn't be so nice to instantiate a big object just to use a little of it's functionality and tight coupling is probably one problem too.

**Comment by MarnuLombard** [comment]
I tend to agree with Peter.
I think that we could do with some separation of responsibilities in the plugins.
As long as we are keeping things DRY across classes.

**Comment by brycelarge** [comment]
I also agree, however look at DiscountCalculator class, the entire class was built for this one line “($this->settings['shipping_discount_percentage'] / 100 * $total);” I just feel in this situation this should be in the service class as it already has all the tools needed for that one line. Here is an example, unit converting to give MDS kg and cm rather than other units of measurement, there is some substance to this and so I extracted that to its own class the “UnitConverter class”, same with cache and the plugin updater. Any way if you guys all still agree that the  DiscountCalculator class should stay then no problem lets merge it in, what do you all think?

**Comment by peterchaula** [comment]
I guess I was over-engineering.

**Pull request merged**
